# Generated by Django 3.0.8 on 2020-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firms',
            name='Cr_number',
            field=models.ImageField(default=False, upload_to='Cr/'),
        ),
        migrations.AlterField(
            model_name='firms',
            name='profile',
            field=models.ImageField(default=False, upload_to='profile/'),
        ),
    ]
