# Generated by Django 3.0.8 on 2020-07-25 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200725_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firms',
            new_name='Firm',
        ),
    ]
