# Generated by Django 3.0.8 on 2020-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_individual_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile_indi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('profile', models.ImageField(default=False, upload_to='Temp/Individual/')),
            ],
        ),
    ]
