# Generated by Django 3.0.8 on 2020-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tempfile_indi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='profile',
            field=models.ImageField(blank=True, default='user.png', upload_to='profile/Individual/'),
        ),
        migrations.AlterField(
            model_name='tempfile_indi',
            name='profile',
            field=models.ImageField(default=False, upload_to='profile/Individual/'),
        ),
    ]
