# Generated by Django 3.0.8 on 2020-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200814_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile_firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('profile', models.ImageField(blank=True, default='user.svg', upload_to='profile/Firm/')),
                ('Cr_number', models.FileField(default=False, upload_to='Cr/')),
            ],
        ),
        migrations.AlterField(
            model_name='individual',
            name='profile',
            field=models.ImageField(blank=True, default='user.svg', upload_to='profile/Individual/'),
        ),
    ]
